package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"gqlgen-app/graph/model"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, name string, password string) (*model.User, error) {
	dbUser := model.DBUser{
		Name:     name,
		Password: password, // In production, hash this!
	}
	if err := DB.Create(&dbUser).Error; err != nil {
		return nil, err
	}
	return &model.User{
		ID:       fmt.Sprintf("%d", dbUser.ID),
		Name:     dbUser.Name,
		Password: dbUser.Password,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, name string, password string) (string, error) {
	var dbUser model.DBUser
	if err := DB.Where("name = ? AND password = ?", name, password).First(&dbUser).Error; err != nil {
		return "", fmt.Errorf("invalid credentials")
	}

	token, err := GenerateToken(dbUser.ID)
	if err != nil {
		return "", err
	}
	return token, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string) (*model.Post, error) {
	// For testing, we use a mock author. In a real app, get from ctx token.
	dbPost := model.DBPost{
		Title:    title,
		Content:  content,
		AuthorID: 1, // hardcoded for test
	}
	if err := DB.Create(&dbPost).Error; err != nil {
		return nil, err
	}

	post := &model.Post{
		ID:      fmt.Sprintf("%d", dbPost.ID),
		Title:   dbPost.Title,
		Content: dbPost.Content,
		Author:  &model.User{ID: "1", Name: "testuser"},
	}

	// Broadcast to all active websocket subscribers!
	r.mu.Lock()
	for _, observer := range r.postObservers {
		observer <- post
	}
	r.mu.Unlock()

	return post, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, title *string, content *string) (*model.Post, error) {
	var dbPost model.DBPost
	if err := DB.First(&dbPost, id).Error; err != nil {
		return nil, err
	}
	if title != nil {
		dbPost.Title = *title
	}
	if content != nil {
		dbPost.Content = *content
	}
	if err := DB.Save(&dbPost).Error; err != nil {
		return nil, err
	}
	return &model.Post{
		ID:      fmt.Sprintf("%d", dbPost.ID),
		Title:   dbPost.Title,
		Content: dbPost.Content,
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	if err := DB.Delete(&model.DBPost{}, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, text string) (*model.Comment, error) {
	var pid uint
	fmt.Sscanf(postID, "%d", &pid)

	dbComment := model.DBComment{
		Text:     text,
		PostID:   pid,
		AuthorID: 1, // hardcoded test user
	}
	if err := DB.Create(&dbComment).Error; err != nil {
		return nil, err
	}

	return &model.Comment{
		ID:   fmt.Sprintf("%d", dbComment.ID),
		Text: dbComment.Text,
	}, nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, text string) (*model.Comment, error) {
	var dbComment model.DBComment
	if err := DB.First(&dbComment, id).Error; err != nil {
		return nil, err
	}
	dbComment.Text = text
	if err := DB.Save(&dbComment).Error; err != nil {
		return nil, err
	}
	return &model.Comment{ID: fmt.Sprintf("%d", dbComment.ID), Text: dbComment.Text}, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	if err := DB.Delete(&model.DBComment{}, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello from GraphQL Server!", nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var dbUsers []model.DBUser
	if err := DB.Find(&dbUsers).Error; err != nil {
		return nil, err
	}
	var users []*model.User
	for _, u := range dbUsers {
		users = append(users, &model.User{ID: fmt.Sprintf("%d", u.ID), Name: u.Name})
	}
	return users, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// In reality, extract user from context
	return &model.User{ID: "1", Name: "Test User"}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	var dbPosts []model.DBPost
	if err := DB.Preload("Author").Find(&dbPosts).Error; err != nil {
		return nil, err
	}
	var posts []*model.Post
	for _, p := range dbPosts {
		posts = append(posts, &model.Post{
			ID:      fmt.Sprintf("%d", p.ID),
			Title:   p.Title,
			Content: p.Content,
			Author:  &model.User{ID: fmt.Sprintf("%d", p.Author.ID), Name: p.Author.Name},
		})
	}
	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	var dbPost model.DBPost
	if err := DB.Preload("Author").Preload("Comments").First(&dbPost, id).Error; err != nil {
		return nil, err
	}
	
	var comments []*model.Comment
	for _, c := range dbPost.Comments {
		comments = append(comments, &model.Comment{ID: fmt.Sprintf("%d", c.ID), Text: c.Text})
	}

	return &model.Post{
		ID:       fmt.Sprintf("%d", dbPost.ID),
		Title:    dbPost.Title,
		Content:  dbPost.Content,
		Author:   &model.User{ID: fmt.Sprintf("%d", dbPost.Author.ID), Name: dbPost.Author.Name},
		Comments: comments,
	}, nil
}

// PostCreated is the resolver for the postCreated field.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	// Create a new channel for this client
	ch := make(chan *model.Post, 1)

	r.mu.Lock()
	if r.postObservers == nil {
		r.postObservers = make(map[string]chan *model.Post)
	}
	id := fmt.Sprintf("%p", ch)
	r.postObservers[id] = ch
	r.mu.Unlock()

	// Clean up when client disconnects
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.postObservers, id)
		r.mu.Unlock()
	}()

	return ch, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch := make(chan *model.Comment, 1)
	// In a real app, track observers per postID. For now, just return the channel.
	go func() {
		<-ctx.Done()
	}()
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateUser(ctx context.Context, name string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}
*/
